### ISSUE TITLE
File name collision error

### ISSUE THREAD

**Issue by Jokendo-collab** [nf-core/rnavar#66] opened 2022-08-08 08:46 UTC
### Description of the bug

I am getting the following error. How can I go around it?
executor >  slurm (52)
[88/01f74d] process > NFCORE_RNAVAR:RNAVAR:PREPAR... [100%] 1 of 1, cached: 1 ✔
[36/aad565] process > NFCORE_RNAVAR:RNAVAR:PREPAR... [100%] 1 of 1, cached: 1 ✔
[22/7db4cc] process > NFCORE_RNAVAR:RNAVAR:PREPAR... [100%] 1 of 1, cached: 1 ✔
[24/9c8095] process > NFCORE_RNAVAR:RNAVAR:INPUT_... [100%] 1 of 1 ✔
[-        ] process > NFCORE_RNAVAR:RNAVAR:CAT_FASTQ -
[ce/f813de] process > NFCORE_RNAVAR:RNAVAR:FASTQC... [100%] 12 of 12, cached:...
[61/b69fc7] process > NFCORE_RNAVAR:RNAVAR:GATK4_... [100%] 1 of 1, cached: 1 ✔
[46/93f930] process > NFCORE_RNAVAR:RNAVAR:GATK4_... [100%] 1 of 1, cached: 1 ✔
[b3/7124a8] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [100%] 12 of 12, cached:...
[46/171a80] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [100%] 12 of 12, cached:...
[67/dd9be3] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [100%] 12 of 12, cached:...
[df/ea5bc6] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [100%] 12 of 12, cached:...
[18/3c1727] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [100%] 12 of 12, cached:...
[ab/aaf983] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [100%] 12 of 12, cached:...
[be/9605cf] process > NFCORE_RNAVAR:RNAVAR:MARKDU... [100%] 12 of 12, cached:...
[5b/b38eaa] process > NFCORE_RNAVAR:RNAVAR:MARKDU... [100%] 12 of 12, cached:...
[c3/c43c99] process > NFCORE_RNAVAR:RNAVAR:MARKDU... [100%] 12 of 12, cached:...
[1e/307cb0] process > NFCORE_RNAVAR:RNAVAR:MARKDU... [100%] 12 of 12, cached:...
[77/2b4569] process > NFCORE_RNAVAR:RNAVAR:MARKDU... [100%] 12 of 12, cached:...
[f9/97c440] process > NFCORE_RNAVAR:RNAVAR:SPLITN... [100%] 6000 of 6000, cac...
[96/179444] process > NFCORE_RNAVAR:RNAVAR:SPLITN... [  4%] 2 of 47
[-        ] process > NFCORE_RNAVAR:RNAVAR:SPLITN... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:GATK4_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:GATK4_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:TABIX     -
[-        ] process > NFCORE_RNAVAR:RNAVAR:GATK4_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:CUSTOM... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:MULTIQC   -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (SRR12670015)'

Caused by:
  Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE` input file name collision -- There are multiple input files for each of the following file names: SRR12670015.bam

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

Failed to invoke `workflow.onComplete` event handler

 -- Check script '/users/javanokendo/.nextflow/assets/nf-core/rnavar/./workflows/rnavar.nf' at line: 458 or see '.nextflow.log' file for more details

### Relevant files

[samplesheet1.csv](https://github.com/nf-core/rnavar/files/9280321/samplesheet1.csv)

### System information

rnavar 1.0.0

**Comment by praveenraj2018** [comment] 2022-08-08 08:51
@Jokendo-collab Could you also upload the .nextflow.log file

**Comment by Jokendo-collab** [comment] 2022-08-08 09:14
Unfortunately, I deleted it when I was trying to remove the junk files.

**Comment by vivischuch** [comment] 2023-11-01 16:09
Hi! I am getting the same error: 

ct-10 20:46:43.710 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:46:43.712 [Task submitter] INFO  nextflow.Session - [4b/61892b] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209)
Oct-10 20:46:56.716 [Task submitter] DEBUG n.processor.TaskPollingMonitor - %% executor local > tasks in the submission queue: 3 -- tasks to be submitted are shown below
~> TaskHandler[id: 1465; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209); status: NEW; exit: -; error: -; workDir: /home/vivischuch/fastq/work/1c/e7d9cab0ecdfff776de82559209410]
~> TaskHandler[id: 1488; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209); status: NEW; exit: -; error: -; workDir: /home/vivischuch/fastq/work/f9/35be1d081142ceaa17c8379c732a63]
~> TaskHandler[id: 1578; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209); status: NEW; exit: -; error: -; workDir: /home/vivischuch/fastq/work/85/56597fed26f7f5999b858bd6fbedfe]
Oct-10 20:49:25.719 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1363; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505204); status: COMPLETED; exit: 0; error: -; workDir: /home/vivischuch/fastq/work/9c/db0ebff4563aa1ea0af39cbb0a55dc]
Oct-10 20:49:25.727 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:49:25.727 [Task submitter] INFO  nextflow.Session - [1c/e7d9ca] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209)
Oct-10 20:49:45.431 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1373; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209); status: COMPLETED; exit: 0; error: -; workDir: /home/vivischuch/fastq/work/4b/61892ba1882b0df047865f1904135a]
Oct-10 20:49:45.436 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:49:45.436 [Task submitter] INFO  nextflow.Session - [f9/35be1d] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209)
Oct-10 20:51:29.888 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1488; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209); status: COMPLETED; exit: 0; error: -; workDir: /home/vivischuch/fastq/work/f9/35be1d081142ceaa17c8379c732a63]
Oct-10 20:51:29.898 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:51:29.898 [Task submitter] INFO  nextflow.Session - [85/56597f] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209)
Oct-10 20:51:33.019 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1465; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209); status: COMPLETED; exit: 0; error: -; workDir: /home/vivischuch/fastq/work/1c/e7d9cab0ecdfff776de82559209410]
Oct-10 20:51:42.836 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1578; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209); status: RUNNING; exit: -; error: -; workDir: /home/vivischuch/fastq/work/85/56597fed26f7f5999b858bd6fbedfe]
Oct-10 20:53:39.370 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1578; name: NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:GATK4_SPLITNCIGARREADS (Severe_preeclampsia_SRR16505209); status: COMPLETED; exit: 0; error: -; workDir: /home/vivischuch/fastq/work/85/56597fed26f7f5999b858bd6fbedfe]
Oct-10 20:53:39.381 [Actor Thread 48] DEBUG nextflow.processor.TaskProcessor - Process NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE > collision check staging file names: [Non-hypertensive_Control_SRR16505217_10scattered.bam:1, Non-hypertensive_Control_SRR16505217_14scattered.bam:1, Non-hypertensive_Control_SRR16505217_21scattered.bam:1, Non-hypertensive_Control_SRR16505217_22scattered.bam:1, Non-hypertensive_Control_SRR16505217_2scattered.bam:1, Non-hypertensive_Control_SRR16505217_4scattered.bam:1, Non-hypertensive_Control_SRR16505217_3scattered.bam:1, Non-hypertensive_Control_SRR16505217_11scattered.bam:1, Non-hypertensive_Control_SRR16505217_20scattered.bam:1, Non-hypertensive_Control_SRR16505217_7scattered.bam:1, Non-hypertensive_Control_SRR16505217_8scattered.bam:1, GRCh38.primary_assembly.genome.fa:1, Non-hypertensive_Control_SRR16505217_18scattered.bam:1, Non-hypertensive_Control_SRR16505217.bam:3, Non-hypertensive_Control_SRR16505217_6scattered.bam:1, Non-hypertensive_Control_SRR16505217_16scattered.bam:1, Non-hypertensive_Control_SRR16505217_17scattered.bam:1, Non-hypertensive_Control_SRR16505217_9scattered.bam:1]
Oct-10 20:53:39.392 [Actor Thread 52] DEBUG nextflow.processor.TaskProcessor - Process NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE > collision check staging file names: [Severe_preeclampsia_SRR16505204_6scattered.bam:1, Severe_preeclampsia_SRR16505204_5scattered.bam:1, Severe_preeclampsia_SRR16505204_2scattered.bam:1, Severe_preeclampsia_SRR16505204_19scattered.bam:1, Severe_preeclampsia_SRR16505204_22scattered.bam:1, Severe_preeclampsia_SRR16505204_21scattered.bam:1, Severe_preeclampsia_SRR16505204_3scattered.bam:1, Severe_preeclampsia_SRR16505204_4scattered.bam:1, Severe_preeclampsia_SRR16505204_20scattered.bam:1, Severe_preeclampsia_SRR16505204_10scattered.bam:1, Severe_preeclampsia_SRR16505208.bam:1, GRCh38.primary_assembly.genome.fa:1, Severe_preeclampsia_SRR16505204_12scattered.bam:1, Severe_preeclampsia_SRR16505204_14scattered.bam:1, Severe_preeclampsia_SRR16505204_13scattered.bam:1, Severe_preeclampsia_SRR16505204_1scattered.bam:1, Severe_preeclampsia_SRR16505204_18scattered.bam:1, Severe_preeclampsia_SRR16505204_24scattered.bam:1, Severe_preeclampsia_SRR16505204.bam:2, Severe_preeclampsia_SRR16505204_9scattered.bam:1]
Oct-10 20:53:39.395 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:53:39.395 [Task submitter] INFO  nextflow.Session - [61/d52348] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505208)
Oct-10 20:53:39.399 [Actor Thread 48] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (8); work-dir=null
  error [nextflow.exception.ProcessUnrecoverableException]: Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE` input file name collision -- There are multiple input files for each of the following file names: Non-hypertensive_Control_SRR16505217.bam
Oct-10 20:53:39.405 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:53:39.405 [Task submitter] INFO  nextflow.Session - [16/8dfbeb] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505229_1scattered)
Oct-10 20:53:39.413 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:53:39.413 [Task submitter] INFO  nextflow.Session - [da/60871b] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505222_10scattered)
Oct-10 20:53:39.430 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:53:39.431 [Task submitter] INFO  nextflow.Session - [f4/6a243c] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505217)
Oct-10 20:53:39.435 [Actor Thread 15] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (47)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/c1/bdfcc75bd154fc6f52521dc6148a98/Severe_preeclampsia_SRR16505234.cram` (pattern: `Severe_preeclampsia_SRR16505234.cram`)
Oct-10 20:53:39.435 [Actor Thread 36] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (34)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/ba/598001c955eb3dc1753c609819df1d/Non-hypertensive_Control_SRR16505206.cram` (pattern: `Non-hypertensive_Control_SRR16505206.cram`)
Oct-10 20:53:39.436 [Actor Thread 15] INFO  nextflow.processor.TaskProcessor - [c1/bdfcc7] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505234)
Oct-10 20:53:39.436 [Actor Thread 36] INFO  nextflow.processor.TaskProcessor - [ba/598001] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505206)
Oct-10 20:53:39.441 [Actor Thread 9] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (39)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/a5/48c99ac926cebab8260593d007dbcc/Severe_preeclampsia_SRR16505210.cram` (pattern: `Severe_preeclampsia_SRR16505210.cram`)
Oct-10 20:53:39.441 [Actor Thread 9] INFO  nextflow.processor.TaskProcessor - [a5/48c99a] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505210)
Oct-10 20:53:39.441 [Actor Thread 38] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (42)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/07/484cd0a47c6d57b75d76b8e44effd6/Severe_preeclampsia_SRR16505211.cram` (pattern: `Severe_preeclampsia_SRR16505211.cram`)
Oct-10 20:53:39.442 [Actor Thread 38] INFO  nextflow.processor.TaskProcessor - [07/484cd0] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505211)
Oct-10 20:53:39.444 [Actor Thread 49] DEBUG nextflow.processor.TaskProcessor - Process NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE > collision check staging file names: [Severe_preeclampsia_SRR16505233_20scattered.bam:1, Severe_preeclampsia_SRR16505233_7scattered.bam:1, Severe_preeclampsia_SRR16505233_22scattered.bam:1, Severe_preeclampsia_SRR16505233_23scattered.bam:1, Severe_preeclampsia_SRR16505233_24scattered.bam:1, Severe_preeclampsia_SRR16505233_8scattered.bam:1, Severe_preeclampsia_SRR16505233_21scattered.bam:1, Severe_preeclampsia_SRR16505233_9scattered.bam:1, Severe_preeclampsia_SRR16505233_18scattered.bam:1, Severe_preeclampsia_SRR16505233_19scattered.bam:1, Severe_preeclampsia_SRR16505233_10scattered.bam:1, Severe_preeclampsia_SRR16505233_12scattered.bam:1, Severe_preeclampsia_SRR16505233_11scattered.bam:1, Severe_preeclampsia_SRR16505233_16scattered.bam:1, Severe_preeclampsia_SRR16505233_15scattered.bam:1, Severe_preeclampsia_SRR16505233_13scattered.bam:1, Severe_preeclampsia_SRR16505233_14scattered.bam:1, Severe_preeclampsia_SRR16505233_1scattered.bam:1, GRCh38.primary_assembly.genome.fa:1, Non-hypertensive_Control_SRR16505217.bam:2, Severe_preeclampsia_SRR16505233_2scattered.bam:1, Severe_preeclampsia_SRR16505233_25scattered.bam:1, Severe_preeclampsia_SRR16505233_6scattered.bam:1, Severe_preeclampsia_SRR16505233_5scattered.bam:1, Severe_preeclampsia_SRR16505233_4scattered.bam:1]
Oct-10 20:53:39.446 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:53:39.447 [Task submitter] INFO  nextflow.Session - [b6/f2260a] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505217)
Oct-10 20:53:39.448 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (38)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/f3/c43bf12d390fc93393e57e48e7922b/Non-hypertensive_Control_SRR16505212.cram` (pattern: `Non-hypertensive_Control_SRR16505212.cram`)
Oct-10 20:53:39.448 [Actor Thread 1] INFO  nextflow.processor.TaskProcessor - [f3/c43bf1] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505212)
Oct-10 20:53:39.449 [Actor Thread 71] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (50)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/17/899fb0a17092053ada62955253bf55/Non-hypertensive_Control_SRR16505221.cram` (pattern: `Non-hypertensive_Control_SRR16505221.cram`)
Oct-10 20:53:39.449 [Actor Thread 71] INFO  nextflow.processor.TaskProcessor - [17/899fb0] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505221)
Oct-10 20:53:39.450 [Actor Thread 46] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (43)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/ae/cde291a1e0a7f50b82bb9df83f62ca/Severe_preeclampsia_SRR16505203.cram` (pattern: `Severe_preeclampsia_SRR16505203.cram`)
Oct-10 20:53:39.450 [Actor Thread 65] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (33)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/4e/5e32fb683b9ec2177d413e0f72f413/Non-hypertensive_Control_SRR16505213.cram` (pattern: `Non-hypertensive_Control_SRR16505213.cram`)
Oct-10 20:53:39.450 [Actor Thread 46] INFO  nextflow.processor.TaskProcessor - [ae/cde291] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505203)
Oct-10 20:53:39.450 [Actor Thread 65] INFO  nextflow.processor.TaskProcessor - [4e/5e32fb] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505213)
Oct-10 20:53:39.450 [Actor Thread 92] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (37)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/f1/112de691194a6f6ccce281bdec24ab/Severe_preeclampsia_SRR16505205.cram` (pattern: `Severe_preeclampsia_SRR16505205.cram`)
Oct-10 20:53:39.450 [Actor Thread 61] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (35)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/6d/6627d514f8ad7d83ac5490f2106a7e/Severe_preeclampsia_SRR16505207.cram` (pattern: `Severe_preeclampsia_SRR16505207.cram`)
Oct-10 20:53:39.450 [Actor Thread 97] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (41)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/26/e03e3fd5e2a709c37d8cf01ea2e975/Severe_preeclampsia_SRR16505216.cram` (pattern: `Severe_preeclampsia_SRR16505216.cram`)
Oct-10 20:53:39.450 [Actor Thread 92] INFO  nextflow.processor.TaskProcessor - [f1/112de6] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505205)
Oct-10 20:53:39.450 [Actor Thread 61] INFO  nextflow.processor.TaskProcessor - [6d/6627d5] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505207)
Oct-10 20:53:39.450 [Actor Thread 83] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (45)` is unable to find [UnixPath]: `/home/vivischuch/fastq/work/7c/43ead70828547504f738059d1c38fa/Severe_preeclampsia_SRR16505228.cram` (pattern: `Severe_preeclampsia_SRR16505228.cram`)
Oct-10 20:53:39.450 [Actor Thread 97] INFO  nextflow.processor.TaskProcessor - [26/e03e3f] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505216)
Oct-10 20:53:39.450 [Actor Thread 83] INFO  nextflow.processor.TaskProcessor - [7c/43ead7] Cached process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Severe_preeclampsia_SRR16505228)
Oct-10 20:53:39.452 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Oct-10 20:53:39.452 [Task submitter] INFO  nextflow.Session - [52/2a3b95] Submitted process > NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (Non-hypertensive_Control_SRR16505214_9scattered)
Oct-10 20:53:39.453 [Actor Thread 48] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE (8)'

Caused by:
  Process `NFCORE_RNAVAR:RNAVAR:SPLITNCIGAR:SAMTOOLS_MERGE` input file name collision -- There are multiple input files for each of the following file names: Non-hypertensive_Control_SRR16505217.bam


Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Oct-10 20:53:39.456 [Actor Thread 48] INFO  nextflow.Session - Execution cancelled -- Finishing pending tasks before exit

**Comment by hakobyansiras** [comment] 2023-12-27 14:35
Any news on this issue?

**Comment by maxulysse** [comment] 2023-12-29 10:51
No update at all.
I'll be closing it since we couldn't reproduce, but please don't hesitate to reopen if you can provide a minimal reproducible example.

**Closed by maxulysse** 2023-12-29 10:51 UTC
Labels: bug
